### ISSUE TITLE
Detailed Design Patterns Consideration

### ISSUE THREAD

**Issue by pureskill714** [pureskill714/ICT2106_P3-2#11]
- [x] Consider two design patterns with changes on the class diagram

- [x] Get feedback from the professor

**Comment by YanRongLee** [comment]
Design pattern has been initially chosen ----- 1. Iterator, 2. Observer

**Comment by JoeEnan** [comment]
Update, chosen Design patterns are Observer for UF04 and Builder for building projects and service centers
